apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: local
    user: postgres
    secureJsonData:
      password: "root1425"
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: false
    editable: true